# Trade Execution

Executes the trade plan generated by `01_analysis_pipeline.ipynb`.
Verifies account state before and after execution.

| Step | Description |
|------|-------------|
| 1 | **Verify State** — confirm account matches notebook 1 snapshot |
| 2 | **Execute** — load trades, edit instructions, place orders |
| 3 | **Verify Execution** — confirm positions match expected state |

**Pre-requisite:** Run `01_analysis_pipeline.ipynb` first. It cleans up
the account (cancels orphan orders, covers shorts) and writes
`portfolio_state.json` — the contract that Step 1 checks.

**Safety checks (built-in):**
- Cancels duplicate orders before placing new ones
- Blocks any sell that would create a short position
- Caps buys to available cash (never goes negative)
- LIMIT GTC orders for outside-hours submission
- 10% trailing stops on all BUY fills

Output: `~/trading/live_portfolio/execution_log.csv`

In [1]:
%load_ext autoreload
%autoreload 2

import sys
from pathlib import Path

import nest_asyncio
import pandas as pd
nest_asyncio.apply()

PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))
sys.path.insert(0, str(PROJECT_ROOT / "notebooks"))

LIVE_DIR = Path.home() / "trading" / "live_portfolio"
TRADE_PLAN_FILE = LIVE_DIR / "trade_plan.csv"
STATE_FILE = LIVE_DIR / "portfolio_state.json"

IB_HOST = "127.0.0.1"
IB_PORT = 4001
IB_CLIENT_ID = 15
TRAILING_STOP_PCT = 10

# ── Limit Order Mode ─────────────────────────────────────
# Set True to use LIMIT GTC orders (submit outside market hours)
# Set False to use MARKET orders (must run during RTH 9:30-16:00 ET)
USE_LIMIT_ORDERS = True      # Recommended for evening/weekend submission
LIMIT_BUFFER_PCT = 1.0       # 1% buffer: BUY at close+1%, SELL at close-1%

print(f"Live dir:    {LIVE_DIR}")
print(f"State file:  {STATE_FILE}")
print(f"Trade plan:  {TRADE_PLAN_FILE}")
print(f"Order mode:  {'LIMIT GTC' if USE_LIMIT_ORDERS else 'MARKET'}")

Live dir:    /home/stuar/trading/live_portfolio
State file:  /home/stuar/trading/live_portfolio/portfolio_state.json
Trade plan:  /home/stuar/trading/live_portfolio/trade_plan.csv
Order mode:  LIMIT GTC

---
## Step 1: Verify State

Connects read-only to IB and confirms the account matches the snapshot
taken by notebook 1 (`portfolio_state.json`):

- Same positions (exact share counts)
- Cash within 2% tolerance (small changes from dividends/interest)
- No open orders (cleanup already ran)
- No short positions
- `trade_plan.csv` checksum matches (file not tampered)

**If FAILED → re-run `01_analysis_pipeline.ipynb` before proceeding.**

In [2]:
from notebooks.scripts.s7_execute import verify_portfolio_state

verification = verify_portfolio_state(
    state_file=STATE_FILE,
    ib_host=IB_HOST,
    ib_port=IB_PORT,
    ib_client_id=IB_CLIENT_ID + 1,  # Read-only client ID
)

if not verification["valid"]:
    critical = [d for d in verification["discrepancies"] if d["severity"] == "CRITICAL"]
    print(f"\n*** STOP: {len(critical)} critical issue(s) found ***")
    print("Re-run 01_analysis_pipeline.ipynb to refresh the state.")
else:
    print("\nState verified — safe to proceed to Step 2.")

State file: /home/stuar/trading/live_portfolio/portfolio_state.json
Generated: 2026-03-19T11:13:56.989976
Account:   U9544585

══════════════════════════════════════════════════
STATE VERIFICATION: PASSED
══════════════════════════════════════════════════
  Positions: 29 expected, 29 actual
  Cash: $65,751 (expected $65,751)
  Open orders: 0
  No discrepancies found
══════════════════════════════════════════════════

State verified — safe to proceed to Step 2.

---
## Step 2: Execute Trades

Three sub-steps:
- **2a** Load trade plan from CSV
- **2b** Optional custom instruction edits + interpret
- **2c** Execute with `CONFIRM=True` gate

**Order modes:**
- `USE_LIMIT_ORDERS = True` (default): LIMIT GTC orders — submit anytime, fills at market open. BUY limits = close + 1%, SELL limits = close - 1%.
- `USE_LIMIT_ORDERS = False`: MARKET orders — must run during RTH (9:30-16:00 ET).

Trailing stops (10% TRAIL, GTC) are placed automatically on every BUY fill/submission.

In [3]:
# Step 2a: Load trade plan
from notebooks.scripts.s7_execute import load_trade_plan

trades = load_trade_plan(TRADE_PLAN_FILE)
print(f"Loaded {len(trades)} trades from {TRADE_PLAN_FILE}")
print(f"Order mode: {'LIMIT GTC' if USE_LIMIT_ORDERS else 'MARKET'}")
if USE_LIMIT_ORDERS:
    print(f"Limit buffer: {LIMIT_BUFFER_PCT}% from last close")
pd.DataFrame(trades)

Loaded 40 trades from /home/stuar/trading/live_portfolio/trade_plan.csv
Order mode: LIMIT GTC
Limit buffer: 1.0% from last close

,action,ticker,name,shares,price,est_value,reason,instruction
0,SELL,DEEF,Xtrackers FTSE Developed ex US Multifactor ETF,103,37.80,3893.40,Not in strategy target,APPROVE
1,SELL,DIM,WisdomTree International MidCap Dividend Fund,47,82.33,3869.51,Not in strategy target,APPROVE
2,SELL,DLS,WisdomTree International SmallCap Dividend Fund,47,82.16,3861.52,Not in strategy target,APPROVE
3,SELL,EFAS,Global X MSCI SuperDividend EAFE ETF,71,20.87,1481.77,Rebalance (drift +0.9%),APPROVE
4,SELL,EWK,iShares MSCI Belgium ETF,78,24.02,1873.56,Not in strategy target,APPROVE
5,SELL,EYLD,Cambria Emerging Shareholder Yield ETF,71,41.38,2937.98,Not in strategy target,APPROVE
6,SELL,FID,First Trust S&P Intl Dividend Aristocrats ETF,91,20.89,1900.99,Rebalance (drift +1.2%),APPROVE
7,SELL,FNDC,Schwab Fundamental Intl Small Equity ETF,63,46.10,2904.30,Not in strategy target,APPROVE
8,SELL,GLDI,UBS ETRACS Gold Shares Covered Call ETN,10,174.82,1748.20,Rebalance (drift +1.1%),APPROVE
9,SELL,IDV,iShares International Select Dividend ETF,82,41.84,3430.88,Not in strategy target,APPROVE
10,SELL,ISVL,iShares Intl Developed Small Cap Value Factor ETF,59,47.89,2825.51,Not in strategy target,APPROVE
11,SELL,JPIN,JPMorgan Diversified Return International Equi...,55,71.05,3907.75,Not in strategy target,APPROVE
12,SELL,ROAM,Hartford Multifactor Emerging Markets ETF,128,31.21,3994.88,Not in strategy target,APPROVE
13,SELL,SCHY,Schwab International Dividend Equity ETF,125,31.39,3923.75,Not in strategy target,APPROVE
14,BUY,AVDV,Avantis International Small Cap Value ETF,49,99.41,4871.09,New position (target 3%),APPROVE
15,BUY,DTH,WisdomTree International High Dividend Fund,16,53.55,856.80,Rebalance (drift -0.5%),APPROVE
16,BUY,DVYA,iShares Asia/Pacific Dividend ETF,188,48.31,9082.28,New position (target 5%),APPROVE
17,BUY,DWX,SPDR S&P International Dividend ETF,22,45.34,997.48,Rebalance (drift -0.6%),APPROVE
18,BUY,ECOW,Pacer Emerging Markets Cash Cows 100 ETF,187,26.26,4910.62,Rebalance (drift -3.0%),APPROVE
19,BUY,FGD,First Trust Dow Jones Global Select Dividend ETF,22,31.50,693.00,Rebalance (drift -0.4%),APPROVE
20,BUY,FIDI,Fidelity International High Dividend ETF,34,27.31,928.54,Rebalance (drift -0.6%),APPROVE
21,BUY,FYLD,Cambria Foreign Shareholder Yield ETF,91,36.69,3338.79,Rebalance (drift -2.0%),APPROVE
22,BUY,GDMA,Gadsden Dynamic Multi-Asset ETF,120,41.05,4926.00,New position (target 3%),APPROVE
23,BUY,GII,State Street SPDR S&P Global Infrastructure ETF,65,75.75,4923.75,New position (target 3%),APPROVE
24,BUY,GWX,State Street SPDR S&P International Small Cap ETF,116,42.57,4938.12,New position (target 3%),APPROVE
25,BUY,ICOW,Pacer Developed Markets International Cash Cow...,117,42.12,4928.04,New position (target 3%),APPROVE
26,BUY,INEQ,Columbia International Equity Income ETF,23,38.55,886.65,Rebalance (drift -0.6%),APPROVE
27,BUY,IYZ,iShares U.S. Telecommunications ETF,127,39.05,4959.35,New position (target 3%),APPROVE
28,BUY,JXI,iShares Global Utilities ETF,57,86.74,4944.18,New position (target 3%),APPROVE
29,BUY,LOPP,Gabelli Love Our Planet & People ETF,144,34.42,4956.48,New position (target 3%),APPROVE
30,BUY,LVHI,Franklin International Low Volatility High Div...,34,39.95,1358.30,Rebalance (drift -0.8%),APPROVE
31,BUY,QTJL,Innovator Growth Accelerated Plus ETF - July,126,39.14,4931.64,New position (target 3%),APPROVE
32,BUY,RODM,Hartford Multifactor Developed Markets (ex-US)...,96,39.15,3758.40,Rebalance (drift -2.3%),APPROVE
33,BUY,SDIV,Global X SuperDividend ETF,53,24.82,1315.46,Rebalance (drift -0.8%),APPROVE
34,BUY,UIVM,VictoryShares Intl Value Momentum ETF,9,68.28,614.52,Rebalance (drift -0.4%),APPROVE
35,BUY,VIDI,Vident International Equity Strategy ETF,4,35.85,143.40,"Rebalance (drift -0.6%) [capped by $50,000 bud...",APPROVE
36,BUY,VWID,Virtus WMC International Dividend ETF,135,36.66,4949.10,New position (target 3%),APPROVE
37,BUY,VYMI,Vanguard Intl High Dividend Yield ETF,11,93.85,1032.35,Rebalance (drift -0.7%),APPROVE
38,BUY,WDIV,SPDR S&P Global Dividend ETF,14,76.91,1076.74,Rebalance (drift -0.7%),APPROVE
39,BUY,WLDR,Affinity World Leaders Equity ETF,187,37.96,7098.52,New position (target 4%),APPROVE

In [6]:
# Step 2b: Custom instructions + interpret
custom_instructions = {
    # "BND": "SKIP",
    # "DIM": "reduce to 30 shares",
}

from notebooks.scripts.s7_execute import apply_custom_instructions, interpret_trades

trades = apply_custom_instructions(trades, custom_instructions)
final_trades = interpret_trades(trades)
print(f"{len(final_trades)} trades ready for execution")
pd.DataFrame(final_trades)

40 trades ready for execution

   ticker action order_type  shares limit_price  ref_price      note
0    DEEF   SELL     MARKET     103        None      37.80  Approved
1     DIM   SELL     MARKET      47        None      82.33  Approved
2     DLS   SELL     MARKET      47        None      82.16  Approved
3    EFAS   SELL     MARKET      71        None      20.87  Approved
4     EWK   SELL     MARKET      78        None      24.02  Approved
5    EYLD   SELL     MARKET      71        None      41.38  Approved
6     FID   SELL     MARKET      91        None      20.89  Approved
7    FNDC   SELL     MARKET      63        None      46.10  Approved
8    GLDI   SELL     MARKET      10        None     174.82  Approved
9     IDV   SELL     MARKET      82        None      41.84  Approved
10   ISVL   SELL     MARKET      59        None      47.89  Approved
11   JPIN   SELL     MARKET      55        None      71.05  Approved
12   ROAM   SELL     MARKET     128        None      31.21  Approved
13   SCHY   SELL     MARKET     125        None      31.39  Approved
14   AVDV    BUY     MARKET      49        None      99.41  Approved
15    DTH    BUY     MARKET      16        None      53.55  Approved
16   DVYA    BUY     MARKET     188        None      48.31  Approved
17    DWX    BUY     MARKET      22        None      45.34  Approved
18   ECOW    BUY     MARKET     187        None      26.26  Approved
19    FGD    BUY     MARKET      22        None      31.50  Approved
20   FIDI    BUY     MARKET      34        None      27.31  Approved
21   FYLD    BUY     MARKET      91        None      36.69  Approved
22   GDMA    BUY     MARKET     120        None      41.05  Approved
23    GII    BUY     MARKET      65        None      75.75  Approved
24    GWX    BUY     MARKET     116        None      42.57  Approved
25   ICOW    BUY     MARKET     117        None      42.12  Approved
26   INEQ    BUY     MARKET      23        None      38.55  Approved
27    IYZ    BUY     MARKET     127        None      39.05  Approved
28    JXI    BUY     MARKET      57        None      86.74  Approved
29   LOPP    BUY     MARKET     144        None      34.42  Approved
30   LVHI    BUY     MARKET      34        None      39.95  Approved
31   QTJL    BUY     MARKET     126        None      39.14  Approved
32   RODM    BUY     MARKET      96        None      39.15  Approved
33   SDIV    BUY     MARKET      53        None      24.82  Approved
34   UIVM    BUY     MARKET       9        None      68.28  Approved
35   VIDI    BUY     MARKET       4        None      35.85  Approved
36   VWID    BUY     MARKET     135        None      36.66  Approved
37   VYMI    BUY     MARKET      11        None      93.85  Approved
38   WDIV    BUY     MARKET      14        None      76.91  Approved
39   WLDR    BUY     MARKET     187        None      37.96  Approved

In [ ]:
# Step 2c: Execute
# ============================================
CONFIRM = True  # Set True to place REAL orders
# ============================================

from notebooks.scripts.s7_execute import execute_trades

exec_results = execute_trades(
    final_trades, LIVE_DIR,
    ib_host=IB_HOST, ib_port=IB_PORT, ib_client_id=IB_CLIENT_ID,
    trailing_stop_pct=TRAILING_STOP_PCT,
    confirm=CONFIRM,
    use_limit_orders=USE_LIMIT_ORDERS,
    limit_buffer_pct=LIMIT_BUFFER_PCT,
)

if exec_results:
    pd.DataFrame(exec_results)

DRY RUN — CONFIRM=False. No orders placed.
Order mode: LIMIT (GTC)
Limit buffer: 1.0% from last close

Would execute 40 trades:
           SELL   103 DEEF   (LIMIT GTC) limit $37.42
           SELL    47 DIM    (LIMIT GTC) limit $81.51
           SELL    47 DLS    (LIMIT GTC) limit $81.34
           SELL    71 EFAS   (LIMIT GTC) limit $20.66
           SELL    78 EWK    (LIMIT GTC) limit $23.78
           SELL    71 EYLD   (LIMIT GTC) limit $40.97
           SELL    91 FID    (LIMIT GTC) limit $20.68
           SELL    63 FNDC   (LIMIT GTC) limit $45.64
           SELL    10 GLDI   (LIMIT GTC) limit $173.07
           SELL    82 IDV    (LIMIT GTC) limit $41.42
           SELL    59 ISVL   (LIMIT GTC) limit $47.41
           SELL    55 JPIN   (LIMIT GTC) limit $70.34
           SELL   128 ROAM   (LIMIT GTC) limit $30.90
           SELL   125 SCHY   (LIMIT GTC) limit $31.08
            BUY    49 AVDV   (LIMIT GTC) limit $100.40
            BUY    16 DTH    (LIMIT GTC) limit $54.09
            BUY   188 DVYA   (LIMIT GTC) limit $48.79
            BUY    22 DWX    (LIMIT GTC) limit $45.79
            BUY   187 ECOW   (LIMIT GTC) limit $26.52
            BUY    22 FGD    (LIMIT GTC) limit $31.82
            BUY    34 FIDI   (LIMIT GTC) limit $27.58
            BUY    91 FYLD   (LIMIT GTC) limit $37.06
            BUY   120 GDMA   (LIMIT GTC) limit $41.46
            BUY    65 GII    (LIMIT GTC) limit $76.51
            BUY   116 GWX    (LIMIT GTC) limit $43.00
            BUY   117 ICOW   (LIMIT GTC) limit $42.54
            BUY    23 INEQ   (LIMIT GTC) limit $38.94
            BUY   127 IYZ    (LIMIT GTC) limit $39.44
            BUY    57 JXI    (LIMIT GTC) limit $87.61
            BUY   144 LOPP   (LIMIT GTC) limit $34.76
            BUY    34 LVHI   (LIMIT GTC) limit $40.35
            BUY   126 QTJL   (LIMIT GTC) limit $39.53
            BUY    96 RODM   (LIMIT GTC) limit $39.54
            BUY    53 SDIV   (LIMIT GTC) limit $25.07
            BUY     9 UIVM   (LIMIT GTC) limit $68.96
            BUY     4 VIDI   (LIMIT GTC) limit $36.21
            BUY   135 VWID   (LIMIT GTC) limit $37.03
            BUY    11 VYMI   (LIMIT GTC) limit $94.79
            BUY    14 WDIV   (LIMIT GTC) limit $77.68
            BUY   187 WLDR   (LIMIT GTC) limit $38.34

Trailing stop: 10% on all BUY fills

---
## Step 3: Verify Execution

Run **after market hours** once all orders should have filled.

Compares actual IB positions against the `expected_post_trade` state from
`portfolio_state.json`. Reports:
- Matched positions (expected = actual)
- Mismatches (wrong share count)
- Unexpected positions (not in plan)
- Pending non-TRAIL orders (LIMIT GTC not yet filled)
- Cash comparison (5% tolerance since fill prices vary)

If incomplete, use the fix cell below to cancel stale orders and resubmit.

In [8]:
from notebooks.scripts.s7_execute import verify_execution

exec_check = verify_execution(
    state_file=STATE_FILE,
    ib_host=IB_HOST,
    ib_port=IB_PORT,
    ib_client_id=IB_CLIENT_ID + 1,
)

if exec_check["complete"]:
    print("\nAll trades executed as expected. Portfolio is on target.")
else:
    print("\nExecution incomplete — run the fix cell below.")
    if exec_check["mismatches"]:
        print(f"  {len(exec_check['mismatches'])} position mismatches")
    if exec_check["pending_orders"]:
        print(f"  {len(exec_check['pending_orders'])} orders still pending")

Connected (read-only): U9544585

══════════════════════════════════════════════════
EXECUTION VERIFICATION: INCOMPLETE
══════════════════════════════════════════════════
  Positions matched:  1 / 30
  Mismatches:         29
    VYMI   expected=52 actual=41 (diff=-11)
    LVHI   expected=136 actual=102 (diff=-34)
    FGD    expected=157 actual=135 (diff=-22)
    GWX    expected=116 actual=0 (diff=-116)
    WLDR   expected=187 actual=0 (diff=-187)
    VIDI   expected=121 actual=117 (diff=-4)
    JXI    expected=57 actual=0 (diff=-57)
    UIVM   expected=72 actual=63 (diff=-9)
    FIDI   expected=181 actual=147 (diff=-34)
    IYZ    expected=127 actual=0 (diff=-127)
    DTH    expected=92 actual=76 (diff=-16)
    LOPP   expected=144 actual=0 (diff=-144)
    GDMA   expected=120 actual=0 (diff=-120)
    DWX    expected=109 actual=87 (diff=-22)
    ECOW   expected=188 actual=1 (diff=-187)
    ICOW   expected=117 actual=0 (diff=-117)
    DVYA   expected=188 actual=0 (diff=-188)
    VWID   expected=135 actual=0 (diff=-135)
    SDIV   expected=213 actual=160 (diff=-53)
    GII    expected=65 actual=0 (diff=-65)
    FID    expected=246 actual=337 (diff=+91)
    AVDV   expected=49 actual=0 (diff=-49)
    QTJL   expected=126 actual=0 (diff=-126)
    RODM   expected=198 actual=102 (diff=-96)
    WDIV   expected=64 actual=50 (diff=-14)
    GLDI   expected=29 actual=39 (diff=+10)
    FYLD   expected=202 actual=111 (diff=-91)
    EFAS   expected=421 actual=492 (diff=+71)
    INEQ   expected=128 actual=105 (diff=-23)
  Unexpected:         11
    FNDC   63 shares
    SCHY   125 shares
    DIM    47 shares
    IDV    82 shares
    JPIN   55 shares
    EWK    78 shares
    ROAM   128 shares
    DEEF   103 shares
    EYLD   71 shares
    DLS    47 shares
    ISVL   59 shares
  Cash: $65,751 (expected $20,886, diff $+44,866)
══════════════════════════════════════════════════

Execution incomplete — run the fix cell below.
  29 position mismatches

In [ ]:
# Step 3b: Fix unfilled orders
#
# Uses check_order_status to identify pending/missing trades,
# then cancels stale orders and resubmits with fresh prices.

# ============================================
CONFIRM_FIX = False  # Set True to cancel + resubmit
# ============================================

from notebooks.scripts.s7_execute import check_order_status, fix_unfilled_orders

check = check_order_status(
    TRADE_PLAN_FILE, LIVE_DIR,
    ib_host=IB_HOST, ib_port=IB_PORT,
    ib_client_id=IB_CLIENT_ID + 1,
)

# Show status
if check["filled"]:
    print("\nFILLED:")
    df_filled = pd.DataFrame(check["filled"])[["action", "ticker", "shares", "fill_status", "fill_price"]]
    display(df_filled.style.set_properties(**{"background-color": "#d4edda"}))

if check["pending"]:
    print("\nPENDING (still working):")
    df_pending = pd.DataFrame(check["pending"])[["action", "ticker", "shares", "ib_status", "limit_price", "filled_qty", "remaining"]]
    display(df_pending.style.set_properties(**{"background-color": "#fff3cd"}))

if check["missing"]:
    print("\nMISSING (needs resubmission):")
    df_missing = pd.DataFrame(check["missing"])[["action", "ticker", "shares", "current_position"]]
    display(df_missing.style.set_properties(**{"background-color": "#f8d7da"}))

# Fix if confirmed
if check["pending"] or check["missing"]:
    fix_results = fix_unfilled_orders(
        check,
        TRADE_PLAN_FILE, LIVE_DIR,
        ib_host=IB_HOST, ib_port=IB_PORT, ib_client_id=IB_CLIENT_ID,
        trailing_stop_pct=TRAILING_STOP_PCT,
        use_limit_orders=USE_LIMIT_ORDERS,
        limit_buffer_pct=LIMIT_BUFFER_PCT,
        confirm=CONFIRM_FIX,
    )
    if fix_results:
        pd.DataFrame(fix_results)
else:
    print("\nNothing to fix — all trades completed.")

---

**Workflow:**
1. Run `01_analysis_pipeline.ipynb` — cleans account, generates trade plan, writes `portfolio_state.json`
2. Run Step 1 — verify state matches
3. Run Step 2 with `CONFIRM=False` — dry run preview
4. Set `CONFIRM=True` — places LIMIT GTC orders
5. After market hours: Run Step 3 — verify fills
6. If anything pending/missing: set `CONFIRM_FIX=True` — cancel stale + resubmit
7. Repeat Steps 3 + fix until all orders filled